baseURL = 'https://jodersky.github.io/applib'
languageCode = 'en-us'
title = "applib"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"

[params]

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://jodersky.github.io/applib"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/jodersky/applib"

[module]
proxy = "direct"
[[module.mounts]]
source="content"
target="content"

[[module.mounts]]
source="../clam/docs"
target="content/docs/clam"
[[module.mounts]]
source="../confuse/docs"
target="content/docs/confuse"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
